// This file was generated by Prisma, and assumes you have installed the
// following:
//   npm install --save-dev prisma dotenv
//
// NOTE FOR PHASE 2 — this file is currently inert.
//
// The Prisma CLI loads `prisma.config.ts`. This is `prisma7.config.ts`, so
// nothing reads it: it was renamed out of the CLI's way when the CLI was pinned
// back to 6.x in 1e78307. It is still inside the TypeScript project, though, so
// `npm run typecheck` and `npm run build` still check it — which is how a
// disabled config file came to be breaking the build.
//
// Two things to settle before Postgres is switched on, and they are the same
// decision:
//
//   1. `@prisma/client` is on 7.10.0 while the `prisma` CLI is on 6.19.3.
//      Those need to match.
//   2. This config-file style is Prisma 7's. Prisma 6 expects the connection
//      URL in the `datasource db` block of `prisma/schema.prisma`, which
//      currently declares only a provider. On 6, put `url = env("DATABASE_URL")`
//      there and delete this file. On 7, rename this back to
//      `prisma.config.ts`.
//
// Until one of those happens, no Prisma command reads a URL from anywhere.

import 'dotenv/config'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // `??` rather than a non-null assertion: `DATABASE_URL` genuinely is unset
    // for most people working on this project, because Phase 1 has no database
    // and the README promises you do not need one. Asserting here would trade a
    // compile error for a runtime crash in `npm run dev`.
    //
    // An empty string is not a valid connection string, so a Prisma command run
    // without `DATABASE_URL` set still fails — with Prisma's own message about
    // the URL, which is the right error for that situation.
    url: process.env['DATABASE_URL'] ?? '',
  },
})
